#!/bin/bash
current_path=`pwd`
rom_script="$current_path/rom-image.ipxe"
ipxe_image_path="$current_path/ipxe_image"
ipxe_path="ipxe"
ipxe_src="$current_path/$ipxe_path/src/"
ipxe_bin="$current_path/$ipxe_path/src/bin"
[ ! -d $ipxe_image_path ] && mkdir $ipxe_image_path
[ ! -d $current_path/$ipxe_path ] && git clone git://git.ipxe.org/ipxe.git $ipxe_path
[ -f $rom_script ] && make -C $ipxe_src EMBEDDED_IMAGE=$rom_script
rm $ipxe_bin/ipxe*.tmp
rm $ipxe_bin/ipxe*.map
cp $ipxe_bin/ipxe* $ipxe_image_path
rm -rf $ipxe_path
