#!/bin/bash



# Load Tux2live setting and functions
cloudboot_root_path=$(cd $(dirname $0) ;pwd)

# Load global configuration 
# It's ini file, not shellconf, replace as
# site_url=`get_conf conf/cloudboot.conf site_url`
#[ -f "$cloudboot_root_path/conf/cloudboot.conf" ] &&  . $cloudboot_root_path/conf/cloudboot.conf

# Load sub function for global usage
[ -f "$cloudboot_root_path/functions.lib" ] &&  . $cloudboot_root_path/functions.lib

#######
# Main
#######

rom_script="$cloudboot_root_path/rom-image.ipxe"
ipxe_image_path="$cloudboot_root_path/cloudboot_img"
ipxe_path="ipxe"
ipxe_src="$cloudboot_root_path/$ipxe_path/src/"
ipxe_bin="$cloudboot_root_path/$ipxe_path/src/bin"
ver=`cat VERSION`

build_rom_script(){

    default_repository=`get_conf default_repository`
    repo_path=`eval echo "$default_repository"_path""`
    repo_url=`eval echo "$default_repository"_url""`
    boot_path=`get_conf $repo_path`
    boot_ip=`get_conf $repo_url`
    cat <<-IPXE > $rom_script
#!gpxe
set filename http://$boot_ip/$boot_path/boot.gpxe.php
:ask_network
echo Welcome to CLOUDBOOT
echo Current Network status:
ifstat
route
echo
prompt --timeout 10000 Press anykey for cloudboot iPXE menu or autoboot after 10 secs && || autoboot
echo a) AUTO config network (Default)
echo b) Manual config network
echo c) Config iPXE all options
echo d) Getting IP address from DHCP Server
echo e) Entering iPXE Shell
read answer
iseq \${answer} a && autoboot ||
iseq \${answer} b && goto setup_ipconfig ||
iseq \${answer} c && config ||
iseq \${answer} d && goto setup_dhcp ||
iseq \${answer} e && shell ||
autoboot 

:setup_dhcp
dhcp && chain \${filename} || goto ask_network

:ask_next
echo a) reset ip address
echo b) back to top menu
read next
iseq \${next} a && goto setup_ipconfig ||
iseq \${next} b && goto ask_network ||

:setup_ipconfig
echo -n which network card you want to config (net0, net1 or netxxx) \${} && read netcard
ifopen \${netcard} || goto setup_ipconfig
isset \${netcard} && echo config \${netcard} || goto setup_ipconfig
:set_ip
echo -n \${netcard} ip address: \${} && read address
set \${netcard}/ip \${address} || goto set_ip
:set_nm
echo -n \${netcard} netmask: \${} && read netmask
set \${netcard}/netmask \${netmask} || goto set_nm
:set_gw
echo -n \${netcard} gateway: \${} && read gateway
set \${netcard}/gateway \${gateway} || goto set_gw
:set_dns
echo -n DNS Server: \${} && read dns
set \${dns} || goto set_dns
echo New network configure:
ifstat
route
echo -n Is it correct? (y/n) \${} && read correct
iseq \${correct} y && chain \${filename} || goto ask_network
iseq \${correct} Y && chain \${filename} || goto ask_network
iseq \${correct} n && goto ask_next ||
iseq \${correct} N && goto ask_next ||

goto ask_network

IPXE
}

copy_rom() {
    keep_ipxe_make_dir=`get_conf keep_ipxe_build_env`
    [ ! -d $ipxe_image_path ] && mkdir $ipxe_image_path
    [ ! -d $cloudboot_root_path/$ipxe_path ] && git clone git://git.ipxe.org/ipxe.git $ipxe_path
    [ -f $rom_script ] && make -C $ipxe_src EMBEDDED_IMAGE=$rom_script
    [ ! $? = "0" ] && echo "make failed , please fix it then do it again!!" && exit 1;
    rm $ipxe_bin/ipxe*.tmp
    rm $ipxe_bin/ipxe*.map
    #ipxe.dsk  ipxe.iso  ipxe.lkrn  ipxe.usb
    #cp $ipxe_bin/ipxe.iso  $ipxe_image_path/cloudboot_$ver.iso
    _patch_iso $ipxe_bin/ipxe.iso  $ipxe_image_path/cloudboot_$ver.iso
    cp $ipxe_bin/ipxe.dsk  $ipxe_image_path/cloudboot_$ver.dsk
    cp $ipxe_bin/ipxe.lkrn $ipxe_image_path/cloudboot_$ver.lkrn
    cp $ipxe_bin/ipxe.usb  $ipxe_image_path/cloudboot_$ver.usb
    [ $keep_ipxe_make_dir == "NO" ] && rm -rf $ipxe_path
}

enable_custom_rom_page(){
    enable_custom_rom=`get_conf enable_custom_rom`
    if [ $enable_custom_rom == 'true' -o $enable_custom_rom == 'TRUE' ]; then
        make -C $ipxe_src bin/NIC
    fi
}

build_rom_script
copy_rom
enable_custom_rom_page
